language: node_js
node_js:
- 16.15.0
branches:
  only:
    - master #设置只监听哪个分支
cache:
  directories:
  - node_modules
install:
- npm install
before_script:

script:
- npm run build:prod

after_script:
  - sh ./deploy.sh
  # git fetch --all && git reset --hard origin/deploy && git pull'

addons:
  ssh_known_hosts: 47.103.212.239 # 添加 SSH 信任列表
after_success: # script 阶段成功时执行
- apt-get -y install sshpass
- sshpass -p 'Hx608136' scp -o stricthostkeychecking=no -r ./dist/* root@47.103.212.239:/paperSubmission/frontend_travis/
# - scp  -o stricthostkeychecking=no -r ./dist/* root@47.103.212.239:/paperSubmission/frontend_travis/  # 使用scp拷贝到服务


branches:
  only:
  - master
