language: node_js
node_js:
- 16.15.0
cache:
  directories:
  - node_modules
install:
- npm install
before_script:

script:
- npm run build:prod

after_script:
  - cd ./dist
  - git init
  - git config user.name "jieye/travis"
  - git config user.email "jieye.ericx@gmail.com"
  - git add -A
  - git commit -m "Travis CI Auto Builder"
  - git push -f https://${gtoken}@github.com/jieye-ericx/conference-submission-system master:deploy
  - cd -
  - ssh root@47.103.212.239 '${pass} && yes && cd /paperSubmission/frontend_travis/ && mkdir aaa'
  # git fetch --all && git reset --hard origin/deploy && git pull'


branches:
  only:
  - master
